"""
Session Manager - Schemas Package (v3.0)
"""

from app.schemas.common import (
    AgentType,
    ConversationHistory,
    ConversationHistoryResponse,
    ConversationTurn,
    ConversationTurnSaveRequest,
    ConversationTurnSaveResponse,
    CustomerProfile,
    ErrorResponse,
    FallbackReason,
    LastEvent,
    ProfileAttribute,
    ProfileGetResponse,
    ResponseType,
    SessionCloseRequest,
    SessionCloseResponse,
    SessionCreateRequest,
    SessionCreateResponse,
    SessionFullResponse,
    SessionPatchRequest,
    SessionPatchResponse,
    SessionResolveRequest,
    SessionResolveResponse,
    SessionState,
    SolApiResultRequest,
    SolDBSTransactionPayload,
    SolDBSTransactionResult,
    StatePatch,
    SubAgentStatus,
    TaskQueueStatus,
    TurnResponse,
)

__all__ = [
    # Common - Enums
    "AgentType",
    "FallbackReason",
    "ResponseType",
    "SessionState",
    "SubAgentStatus",
    "TaskQueueStatus",
    # Common - Models
    "ConversationHistory",
    "ConversationHistoryResponse",
    "ConversationTurn",
    "ConversationTurnSaveRequest",
    "ConversationTurnSaveResponse",
    "CustomerProfile",
    "ErrorResponse",
    "LastEvent",
    "ProfileAttribute",
    "ProfileGetResponse",
    "SessionCloseRequest",
    "SessionCloseResponse",
    "SessionCreateRequest",
    "SessionCreateResponse",
    "SessionPatchRequest",
    "SessionPatchResponse",
    "SessionResolveRequest",
    "SessionResolveResponse",
    "SessionFullResponse",
    "StatePatch",
    # 실시간 API 연동 결과 저장 (Sprint 3+)
    "TurnResponse",
    "SolDBSTransactionPayload",
    "SolDBSTransactionResult",
    "SolApiResultRequest",
]
