name: Build Push & Update Chart Repo

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        pip install --upgrade uv

    - name: Sync dependencies
      run: |
        uv sync

    - name: Set image tag
      run: |
        echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "IMAGE_NAME=${{ github.event.repository.name }}" | sed 's/^IMAGE_NAME=shinhanbank-sol-/IMAGE_NAME=/' >> $GITHUB_ENV

    - name: Login to ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login \
        ${{ secrets.ACR_LOGIN_SERVER }} \
        -u ${{ secrets.ACR_USERNAME }} \
        --password-stdin

    - name: Build & Push Image
      run: |
        docker build -t \
          ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} .
        docker push \
          ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

    - name: Checkout Helm chart repo
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.CHART_REPO }}
        token: ${{ secrets.CHART_TOKEN }}
        path: chart

    - name: Update values.yaml
      run: |
        sed -i "s/tag:.*/tag: \"${{ env.TAG }}\"/" \
          chart/${{ secrets.CHART_PATH }}/values.yaml

    - name: Commit & Push chart repo
      run: |
        cd chart
        git config user.name "Shinhanbank-SOL-CI-Bot"
        git config user.email "SHB-SOL-CI-Bot@noreply.github.com"
        git add .
        git commit -m "Update image tag to ${{ env.TAG }}"
        git push
